package matt.model.redis

import kotlinx.serialization.Serializable
import kotlin.reflect.full.declaredMemberProperties

/*
FOR REDIS VERSION 7
fields acquired by using `config get *` on my local redis 7 server
*/
@Serializable
data class RedisConfigurationPatch(
    val `min-replicas-max-lag`: Int? = null,
    val `active-defrag-cycle-max`: Int? = null,
    val `client-output-buffer-limit`: String? = null,
    val `active-expire-effort`: Int? = null,
    val `min-slaves-max-lag`: Int? = null,
    val `cluster-announce-ip`: String? = null,
    val `min-replicas-to-write`: Int? = null,
    val `syslog-enabled`: Boolean? = null,
    val `hash-max-ziplist-entries`: Int? = null,
    val `cluster-slave-no-failover`: Boolean? = null,
    val `tls-ciphers`: String? = null,
    val `latency-monitor-threshold`: Int? = null,
    val `cluster-replica-no-failover`: Boolean? = null,
    val `tls-dh-params-file`: String? = null,
    val slaveof: String? = null,
    val `cluster-replica-validity-factor`: Int? = null,
    val `slave-priority`: Int? = null,
    val `list-max-listpack-size`: Int? = null,
    val `auto-aof-rewrite-percentage`: Int? = null,
    val `tls-client-key-file-pass`: String? = null,
    val `syslog-facility`: String? = null,
    val `cluster-port`: Int? = null,
    val `tls-ca-cert-file`: String? = null,
    val `aof-rewrite-incremental-fsync`: Boolean? = null,
    val `hash-max-ziplist-value`: Int? = null,
    val `cluster-link-sendbuf-limit`: Int? = null,
    val `slave-ignore-maxmemory`: Boolean? = null,
    val rdbchecksum: Boolean? = null,
    val timeout: Int? = null,
    val `tls-replication`: Boolean? = null,
    val bind: String? = null,
    val `repl-disable-tcp-nodelay`: Boolean? = null,
    val `crash-log-enabled`: Boolean? = null,
    val `enable-module-command`: Boolean? = null,
    val `lazyfree-lazy-eviction`: Boolean? = null,
    val `lazyfree-lazy-user-flush`: Boolean? = null,
    val `tracking-table-max-keys`: Int? = null,
    val `propagation-error-behavior`: String? = null,
    val `repl-diskless-sync`: Boolean? = null,
    val `stream-node-max-bytes`: Int? = null,
    val `replica-priority`: Int? = null,
    val `tls-cluster`: Boolean? = null,
    val `always-show-logo`: Boolean? = null,
    val `aof-disable-auto-gc`: Boolean? = null,
    val `enable-debug-command`: Boolean? = null,
    val maxclients: Int? = null,
    val `replica-announce-ip`: String? = null,
    val dbfilename: String? = null,
    val `lazyfree-lazy-server-del`: Boolean? = null,
    val `lazyfree-lazy-user-del`: Boolean? = null,
    val `active-defrag-threshold-upper`: Int? = null,
    val `auto-aof-rewrite-min-size`: Int? = null,
    val `shutdown-timeout`: Int? = null,
    val `set-max-intset-entries`: Int? = null,
    val `replica-serve-stale-data`: Boolean? = null,
    val `tls-ca-cert-dir`: String? = null,
    val `cluster-announce-hostname`: String? = null,
    val `acllog-max-len`: Int? = null,
    val `repl-diskless-load`: String? = null,
    val `maxmemory-samples`: Int? = null,
    val `disable-thp`: Boolean? = null,
    val `acl-pubsub-default`: String? = null,
    val `lfu-log-factor`: Int? = null,
    val `cluster-slave-validity-factor`: Int? = null,
    val `socket-mark-id`: Int? = null,
    val `shutdown-on-sigint`: String? = null,
    val `oom-score-adj`: Boolean? = null,
    val `stream-node-max-entries`: Int? = null,
    val `zset-max-ziplist-entries`: Int? = null,
    val port: Int? = null,
    val `tcp-keepalive`: Int? = null,
    val `repl-ping-replica-period`: Int? = null,
    val `cluster-announce-bus-port`: Int? = null,
    val daemonize: Boolean? = null,
    val `no-appendfsync-on-rewrite`: Boolean? = null,
    val logfile: String? = null,
    val `notify-keyspace-events`: String? = null,
    val `tls-client-key-file`: String? = null,
    val `active-defrag-threshold-lower`: Int? = null,
    val activerehashing: Boolean? = null,
    val appendfsync: String? = null,
    val `io-threads-do-reads`: Boolean? = null,
    val `slowlog-max-len`: Int? = null,
    val `tls-session-cache-size`: Int? = null,
    val `slave-announce-ip`: String? = null,
    val rdbcompression: Boolean? = null,
    val `sanitize-dump-payload`: Boolean? = null,
    val `maxmemory-policy`: String? = null,
    val `slowlog-log-slower-than`: Int? = null,
    val server_cpulist: String? = null,
    val `client-query-buffer-limit`: Int? = null,
    val `active-defrag-cycle-min`: Int? = null,
    val `hll-sparse-max-bytes`: Int? = null,
    val `repl-backlog-ttl`: Int? = null,
    val activedefrag: Boolean? = null,
    val bgsave_cpulist: String? = null,
    val `proto-max-bulk-len`: Long? = null,
    val `repl-diskless-sync-max-replicas`: Int? = null,
    val pidfile: String? = null,
    val `enable-protected-configs`: Boolean? = null,
    val `zset-max-listpack-entries`: Int? = null,
    val `maxmemory-eviction-tenacity`: Int? = null,
    val `repl-backlog-size`: Long? = null,
    val `replica-lazy-flush`: Boolean? = null,
    val `cluster-preferred-endpoint-type`: String? = null,
    val save: String? = null,
    val appenddirname: String? = null,
    val `busy-reply-threshold`: Int? = null,
    val `active-defrag-ignore-bytes`: Long? = null,
    val `oom-score-adj-values`: String? = null,
    val `syslog-ident`: String? = null,
    val `io-threads`: Int? = null,
    val loglevel: String? = null,
    val `min-slaves-to-write`: Int? = null,
    val `protected-mode`: Boolean? = null,
    val `cluster-node-timeout`: Int? = null,
    val hz: Int? = null,
    val `slave-lazy-flush`: Boolean? = null,
    val `list-compress-depth`: Int? = null,
    val `zset-max-ziplist-value`: Int? = null,
    val `slave-read-only`: Boolean? = null,
    val `stop-writes-on-bgsave-error`: Boolean? = null,
    val `hash-max-listpack-entries`: Int? = null,
    val `lua-time-limit`: Int? = null,
    val `slave-announce-port`: Int? = null,
    val `ignore-warnings`: String? = null,
    val `cluster-require-full-coverage`: Boolean? = null,
    val aclfile: String? = null,
    val `lazyfree-lazy-expire`: Boolean? = null,
    val `repl-ping-slave-period`: Int? = null,
    val `tls-protocols`: String? = null,
    val `cluster-enabled`: Boolean? = null,
    val `rdb-del-sync-files`: Boolean? = null,
    val unixsocketperm: Int? = null,
    val `replica-ignore-disk-write-errors`: Boolean? = null,
    val bio_cpulist: String? = null,
    val `bind-source-addr`: String? = null,
    val `tls-key-file-pass`: String? = null,
    val masterauth: String? = null,
    val unixsocket: String? = null,
    val `cluster-config-file`: String? = null,
    val databases: Int? = null,
    val `zset-max-listpack-value`: Int? = null,
    val `tls-client-cert-file`: String? = null,
    val `tls-prefer-server-ciphers`: Boolean? = null,
    val `replica-announced`: Boolean? = null,
    val `repl-timeout`: Int? = null,
    val `tcp-backlog`: Int? = null,
    val aof_rewrite_cpulist: String? = null,
    val `replica-read-only`: Boolean? = null,
    val `cluster-migration-barrier`: Int? = null,
    val `lfu-decay-time`: Int? = null,
    val `aof-timestamp-enabled`: Boolean? = null,
    val `tls-key-file`: String? = null,
    val `replica-announce-port`: Int? = null,
    val `aof-load-truncated`: Boolean? = null,
    val supervised: Boolean? = null,
    val `cluster-announce-port`: Int? = null,
    val `proc-title-template`: String? = null,
    val `list-max-ziplist-size`: Int? = null,
    val `tls-auth-clients`: Boolean? = null,
    val `tls-port`: Int? = null,
    val `aof-use-rdb-preamble`: Boolean? = null,
    val `active-defrag-max-scan-fields`: Int? = null,
    val `maxmemory-clients`: Int? = null,
    val `dynamic-hz`: Boolean? = null,
    val `latency-tracking-info-percentiles`: String? = null,
    val appendfilename: String? = null,
    val `cluster-allow-reads-when-down`: Boolean? = null,
    val maxmemory: Int? = null,
    val `hash-max-listpack-value`: Int? = null,
    val `tls-session-cache-timeout`: Int? = null,
    val `cluster-allow-replica-migration`: Boolean? = null,
    val `cluster-allow-pubsubshard-when-down`: Boolean? = null,
    val `latency-tracking`: Boolean? = null,
    val `set-proc-title`: Boolean? = null,
    val `rdb-save-incremental-fsync`: Boolean? = null,
    val `jemalloc-bg-thread`: Boolean? = null,
    val `cluster-announce-tls-port`: Int? = null,
    val appendonly: Boolean? = null,
    val `repl-diskless-sync-delay`: Int? = null,
    val replicaof: String? = null,
    val `replica-ignore-maxmemory`: Boolean? = null,
    val `shutdown-on-sigterm`: String? = null,
    val `slave-serve-stale-data`: Boolean? = null,
    val dir: String? = null,
    val masteruser: String? = null,
    val `crash-memcheck-enabled`: Boolean? = null,
    val `tls-session-caching`: Boolean? = null,
    val `tls-ciphersuites`: String? = null,
    val `tls-cert-file`: String? = null,
    val requirepass: String? = null
) {
    fun nonNullProperties(): Map<String, String> {
        val props = RedisConfigurationPatch::class.declaredMemberProperties

        val toRewrite =
            props.mapNotNull {
                val v = it.get(this)
                if (v != null) {
                    val k = it.name
                    val s =
                        if (v is Boolean) {
                            if (v) "yes" else "no"
                        } else {
                            v.toString()
                        }
                    k to s
                } else {
                    null
                }
            }.toMap()

        return toRewrite
    }
}
